name: 'watchr-action: Automated Monitoring'
description: 'Monitor your domain and certificates from GitHub Actions'
author: 'Flavio Heleno <flaviohbatista@gmail.com>'

branding:
  icon: 'activity'
  color: 'blue'

inputs:
  check:
    description: One of the available watchr checks (eg. domain, certificate)
    required: true
  domain:
    description: The domain name to be checked (root domain for `check:domain` or FQDN for `check:certificate`)
    required: true
  expiration_threshold: Number of days left to domain or certificate expiration that will trigger an error
    required: false
    default: 5
  registrar_name: Match the domain Registrar Name (for `check:domain`)
    required: false
  status_codes: List of Extensible Provisioning Protocol (EPP) status codes that should be active (CSV format)
    required: false
    default: clientTransferProhibited
  issuer_name: Match the certificate Issuer Name (for `check:certificate)
    required: false
  fingerprint: Match the certificate SHA-256 Fingerprint (for `check:certificate)
    required: false
  serial_number: Match the certificate Serial Number (for `check:certificate)
    required: false
outputs:
  status:
    description: The exit code returned by watchr check
  stdout:
    description: The stdout output generated by watchr check

runs:
  using: 'docker'
  image: 'docker://ghcr.io/flavioheleno/watchr-action:v0.1.0'
